on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Update submodules
      run: git submodule update --init --recursive
    - name: npm install and run coverage
      run: |
        npm install
        npm test

    - name: Coveralls
      uses: coverallsapp/github-action@v2.3.6
